### ISSUE TITLE
Wallet secrets and seeds exposed

### ISSUE THREAD

**Issue by juliangums** [AlexanderBuzz/xrpl-php#1]
@AlexanderBuzz  I came across your project when looking for an XRPL PHP SDK.
I went through your code and saw this:
https://github.com/AlexanderBuzz/xrpl-php/blob/081904370e48be5761ae553c08175e62f9c75391/src/Wallet/Wallet.php#L28-L32

You might want to stick this in an .env file and use a different wallet going forward. This one is now compromised.

**Comment by AlexanderBuzz** [comment]
This is standard test data from the documentation, no secretes here :)

**Comment by juliangums** [comment]
@AlexanderBuzz not sure what docs you're referring to. One can steal 22 XRP from it and issue more VRB and VSD token with the above info. If that's not an issue, ok. But thought I'd let you know.

**Comment by AlexanderBuzz** [comment]
@juliangums In the [JavaScript documentation](https://xrpl.org/get-started-using-javascript.html)
