### ISSUE TITLE
Get the OrderBook for a token

### ISSUE THREAD

**Issue by nicoeni** [AlexanderBuzz/xrpl-php#10]
Hi, How can I get an OrderBook for an IOU? IN Javascript I can to this with the code below:

    objet = {
      command: "book_offers",
      taker_gets: {
        currency: "XRP",
      },
      taker_pays: {
        currency: currency,
        issuer: issuer,
      },
      limit: 150,
    };

    orders = await client.request(objet);
    
    Thank you

**Comment by nicoeni** [comment]
Thank you for your answer, but it doesn't work. I have a message error:

"$body must be a string, Array given"

**Comment by AlexanderBuzz** [comment]
Ah, you have to json_encode($body), then it should work!

**Comment by nicoeni** [comment]
Hello, it's not working, I have this error message:

Fatal error: Uncaught GuzzleHttp\Exception\ClientException: Client error: `POST https://xrplcluster.com/` resulted in a `400 Bad Request` response: params unparseable ...

I try do do a  "command" => "book_offers" and not a "method" => "offer_create"

Thank you

**Comment by nicoeni** [comment]
Hello, how could I transform this

$tx = [    
    "taker_gets"=> ["currency"=> "XRP"],
    "taker_pays" => [
      "currency"=> "IOU",
      "issuer"=> "r...",
    ],
    "limit" => 10
  ];

into a blob

Thank you

**Comment by nicoeni** [comment]
Ok, I found a way to do it. Thank you for your help.
