### ISSUE TITLE
Model SubmitRequest not found after commit 43d513a

### ISSUE THREAD

**Issue by nvonsternberg** [AlexanderBuzz/xrpl-php#17]
Hi, thanks for the great library. 

Running master or tags after 0.7.1 I get this error 

```
--- NFT Testnet example ---
Created standby wallet - address: rPDbiiPi8YAALacaAdqv5diG1wnR4amD39 seed: 
PHP Fatal error:  Uncaught Error: Class "XRPL_PHP\Models\ServerInfo\SubmitRequest" not found in /home/n/git/xrpl-php/src/Sugar/submit.php:38
Stack trace:
#0 /home/n/git/xrpl-php/src/Sugar/submit.php(271): XRPL_PHP\Sugar\submitRequest()
#1 /home/n/git/xrpl-php/src/Client/JsonRpcClient.php(252): XRPL_PHP\Sugar\submitAndWait()
#2 /home/n/git/xrpl-php/examples/quickstart/3.mint-nfts.php(40): XRPL_PHP\Client\JsonRpcClient->submitAndWait()
#3 {main}
  thrown in /home/n/git/xrpl-php/src/Sugar/submit.php on line 38
```

The file indeed does exist. 

It looks like you might have intended to move the file in this commit https://github.com/AlexanderBuzz/xrpl-php/commit/43d513a16413e491e4c323e5a633711d91da676f but the changes only show the deletion of `SubmitRequest`

You should be able to reproduce by running the mint_nfts example. 

Thanks!

**Comment by AlexanderBuzz** [comment]
Hey Nick, I'm on it!

**Comment by AlexanderBuzz** [comment]
@nvonsternberg Ok, there was a namespace Error after the restructuring of the method classes. Thanks for pointing that out!
