### ISSUE TITLE
Not able to retreive an account with seed

### ISSUE THREAD

**Issue by nicoeni** [AlexanderBuzz/xrpl-php#19]
Hi, I created a wallet with Xumm, and when I try to retrieve the account with your API, I have this error:

Fatal error: Uncaught Exception: Checksum does not validate in C:\xampp\htdocs\AD\vendor\hardcastle\xrpl_php\src\Core\RippleAddressCodec\Codec.php:86 Stack trace: #0 C:\xampp\htdocs\AD\vendor\hardcastle\xrpl_php\src\Core\RippleAddressCodec\Codec.php(35): XRPL_PHP\Core\RippleAddressCodec\Codec->decodeChecked('s.......') #1 C:\xampp\htdocs\AD\vendor\hardcastle\xrpl_php\src\Core\RippleAddressCodec\CodecWithXrpAlphabet.php(70): XRPL_PHP\Core\RippleAddressCodec\Codec->decode('s.......', Array) #2 C:\xampp\htdocs\AD\vendor\hardcastle\xrpl_php\src\Core\CoreUtilities.php(111): XRPL_PHP\Core\RippleAddressCodec\CodecWithXrpAlphabet->decodeSeed('s.......') #3 C:\xampp\htdocs\AD\vendor\hardcastle\xrpl_php\src\Wallet\Wallet.php(85): XRPL_PHP\Core\CoreUtilities::decodeSeed('s.......') #4 C:\xampp\htdocs\AD\vendor\hardcastle\xrpl_php\src\Wallet\Wallet.php(73): XRPL_PHP\Wallet\Wallet::deriveWallet('s.......') #5 C:\xampp\htdocs\AD\a1.php(32): XRPL_PHP\Wallet\Wallet::fromSeed('s.......') #6 {main} thrown in C:\xampp\htdocs\AD\vendor\hardcastle\xrpl_php\src\Core\RippleAddressCodec\Codec.php on line 86

I don't know why it's not work

Thank you for your great job

Nicolas

**Comment by AlexanderBuzz** [comment]
@nicoeni As the Wallet::fromSeed takes a secret value and we obviously can't share this here, lets try it in Javascript. It would look like this:

```javascript
const xrpl =  require('xrpl');

const wallet = xrpl.Wallet.fromSeed(''your-secret-seed);

console.log(wallet.address);
```

**Comment by AlexanderBuzz** [comment]
If we can rule out a typo that way, it would be interesting which network on XUMM (Main, Test, XAHAU etc.) you've used, so I can try to reproduce the error.

**Comment by nicoeni** [comment]
Hi, I wasn't able to have the same issue again. I close the ticket. Thank you
