### ISSUE TITLE
Unable to install your package with composer

### ISSUE THREAD

**Issue by nicoeni** [AlexanderBuzz/xrpl-php#2]
Hi, I try to communicate with xrpl in php to decode a blob text and I found your project. 
Could you explain how to install your project with composer please?

Thank you for your work

Nicolas

**Comment by nicoeni** [comment]
composer require gndlf/xrpl_php doesn't work for me

**Comment by AlexanderBuzz** [comment]
Hi nicoeni, PHP_XRPL is at the moment work in progress, which will likely be feature complete in mid September and production ready a couple of weeks later. The current Packagist package seems to be auto-generated and is not yet curated, of course I have that on my roadmap. I will have a look at that though, all the low-level stuff has been coded and currently I am working on the actual methods/requests. I you want to toy around with it now, you could try to get it to run via docker, an example on how to encode and decode a Blob can be found in the tests.

**Comment by nicoeni** [comment]
Hi, thank you for your answer. I try to make a login with Xumm on a website. So I have a blob and want to get the user wallet. I tried with xrpl.js on front-end but it doesn't work, so I want to try on backend and use your package. I will wait it.Thank youNicolasLe 22 août 2022 17:30, AlexanderBuzz ***@***.***> a écrit :
Hi nicoeni, PHP_XRPL is at the moment work in progress, which will likely be feature complete in mid September and production ready a couple of weeks later. The current Packagist package seems to be auto-generated and is not yet curated, of course I have that on my roadmap. I will have a look at that though, all the low-level stuff has been coded and currently I am working on the actual methods/requests. I you want to toy around with it now, you could try to get it to run via docker, an example on how to encode and decode a Blob can be found in the tests.

**Comment by AlexanderBuzz** [comment]
@nicoeni You can install the package via composer with `composer require hardcastle/xrpl_php dev-master` Note that the package is available but not officially released yet.
