### ISSUE TITLE
orderbook

### ISSUE THREAD

**Issue by JohnGabrielRodi** [AlexanderBuzz/xrpl-php#22]
Hi. Are the orderbook code sections incomplete?

**Comment by AlexanderBuzz** [comment]
Hi John, the PathFind method is "websockets only", so this one is not implemented in XRPL_PHP. AMM amendment is coming this week. Have  I overlooked something?

**Comment by AlexanderBuzz** [comment]
@JohnGabrielRodi AMM is in, I'm gonna close the issue
