### ISSUE TITLE
DestinationTag in payment

### ISSUE THREAD

**Issue by nicoeni** [AlexanderBuzz/xrpl-php#23]
Hi, I can't make a payment with a DestinationTag, even if  I put it in the $tx object. How can I fix that?
Thank you

Nicolas

**Comment by AlexanderBuzz** [comment]
Hi, which version are you using? Is this happening with the most recent version? There should be a fix for that a couple of weeks ago.

**Comment by nicoeni** [comment]
I update my version with the last one, but I still can't see a DestinationTag

**Comment by nicoeni** [comment]
I update with the last version and it works. 
Thank you
