### ISSUE TITLE
Longer Currency Codes

### ISSUE THREAD

**Issue by JohnGabrielRodi** [AlexanderBuzz/xrpl-php#26]
Does this SDK support longer currency names in hex for custom tokens?

Like "Dropzop" token instead of "DZT"

I'm not able to get it working.

**Comment by AlexanderBuzz** [comment]
Hi @JohnGabrielRodi, yes it does, I'll make an example for that!

**Comment by AlexanderBuzz** [comment]
@JohnGabrielRodi  If go to the examples folder, you can create an example setup with:

`console
php token-create.php --tokenName 44726F707A6F7000000000000000000000000000 --issuerBalance 100000 --customerBalance 1000
`

Example Bithomp test account: https://test.bithomp.com/explorer/r9PvAD9TeGv3huQ1Tku9deTpSBHQ9QtFdS

I'll publish a new package with a helper function ASAP,  but if you need "Dropzop', its custom currency value is "44726F707A6F7000000000000000000000000000", which is basically a packed and padded string.

**Comment by AlexanderBuzz** [comment]
It is now avaliable in the latest Package, see examples/custom_currency_codes.php
