### ISSUE TITLE
incorrect  BaseResponse::getStatus() return type definition

### ISSUE THREAD

**Issue by wild-man** [AlexanderBuzz/xrpl-php#27]
`
Hardcastle\XRPL_PHP\Models\BaseResponse
    public function getStatus(): array
    {
        return $this->result['status'];
    }
`
 $this->result['status'] is string in ripple node answer 
Error: Hardcastle\XRPL_PHP\Models\BaseResponse::getStatus(): Return value must be of type array, string returned
on valid results

**Comment by AlexanderBuzz** [comment]
Ok, looking into it...

**Comment by AlexanderBuzz** [comment]
Fixed as in versino 0.9.4
