### ISSUE TITLE
Brick Math v0.12.x support

### ISSUE THREAD

**Issue by zgrguric** [AlexanderBuzz/xrpl-php#29]
Allow support for brick/math 0.12.x dependency - also leave also 0.11.x to be also installable in the same time.

Laravel 11 (default installation) has dep. 0.12 brick math by default trough some used packages.

**Comment by zgrguric** [comment]
suggestion
`"brick/math": "^0.11|^0.12"`

**Comment by AlexanderBuzz** [comment]
Ok, suggestion approved (Release 0.9.5)
