### ISSUE TITLE
Send IOU under 1 token

### ISSUE THREAD

**Issue by nicoeni** [AlexanderBuzz/xrpl-php#7]
Hi, 
when I try to send under 1 token, for example 0.1 of an IOU, it sends 1 token. 
Is it the minimum to send?

Thank you

Nicolas

**Comment by AlexanderBuzz** [comment]
@nicoeni Well, that looks like a bug - thanks for pointing that out, I will have a look at it

**Comment by AlexanderBuzz** [comment]
@nicoeni It is fixed now!

**Comment by nicoeni** [comment]
Thank youLe 7 déc. 2022 11:01, AlexanderBuzz ***@***.***> a écrit :
@nicoeni It is fixed now!
