### ISSUE TITLE
Upgrade PHPUnit to ^10.1

### ISSUE THREAD

**Issue by zgrguric** [AlexanderBuzz/xrpl-php#9]
No rush.

**Comment by AlexanderBuzz** [comment]
I will have a look, maybe a good opportunity to get rid of the pre-release flag and mark the thing as stable...

**Comment by AlexanderBuzz** [comment]
So, this has been updated in the latest release, also the dependecies on certain system extensions have been removed

**Comment by zgrguric** [comment]
Thanks!
